In [1]:
import sys
sys.path.append('../build')
import numpy as np
import libry as ry

Define a function to compute differentiable features

In [2]:
#the function needs to have the signature (array) -> (array, array) with dimensionalities (n) -> (d, d-times-n)
def sqrPot(x):
    y = np.array(x)
    y[0] = y[0] - 1.
    J = np.eye(y.size)
    return y,J

Define a NLP (non-linear mathematical program)

In [7]:
nlp = ry.NLP_Factory()
nlp.setDimension(3)
nlp.setBounds([-2,-2,-2],[2,2,2])
nlp.setFeatureTypes([ry.OT.sos, ry.OT.sos, ry.OT.sos])
nlp.setEvalCallback(sqrPot)

In [8]:
nlp.testCallingEvalCallback(nlp.getInitializationSample())

(array([-1.87339878, -0.32094097,  1.82815742]), array([[ 1.,  0.,  0.],
        [ 0.,  1.,  0.],
        [ 0.,  0.,  1.]]))

Define a solver

In [9]:
solver = ry.NLP_Solver()
solver.setProblem(nlp)
solver.setSolver(ry.NLP_SolverID.newton)

In [10]:
solver.solve(True)

array([  9.96915092e-01,   1.36573836e-04,  -1.73920835e-03])

In [13]:
solver.getTrace_x()

array([[ -1.64987755e+00,   1.17314339e-01,  -1.49394703e+00],
       [ -1.44987755e+00,   1.08460017e-01,  -1.38119110e+00],
       [ -1.24987755e+00,   9.96056957e-02,  -1.26843517e+00],
       [ -1.04987755e+00,   9.07513742e-02,  -1.15567924e+00],
       [ -8.49877548e-01,   8.18970527e-02,  -1.04292331e+00],
       [ -6.49877548e-01,   7.30427312e-02,  -9.30167382e-01],
       [ -4.49877548e-01,   6.41884097e-02,  -8.17411453e-01],
       [ -2.49877548e-01,   5.53340882e-02,  -7.04655523e-01],
       [ -4.98775482e-02,   4.64797667e-02,  -5.91899594e-01],
       [  1.50122452e-01,   3.76254452e-02,  -4.79143664e-01],
       [  3.50122452e-01,   2.87711237e-02,  -3.66387735e-01],
       [  5.50122452e-01,   1.99168022e-02,  -2.53631805e-01],
       [  7.50122452e-01,   1.10624807e-02,  -1.40875876e-01],
       [  9.16707484e-01,   3.68749358e-03,  -4.69586253e-02],
       [  9.72235828e-01,   1.22916453e-03,  -1.56528751e-02],
       [  9.90745276e-01,   4.09721509e-04,  -5.2176250

In [12]:
solver.getTrace_costs()

array([[  9.26749140e+00,   0.00000000e+00,   0.00000000e+00],
       [  7.92135243e+00,   0.00000000e+00,   0.00000000e+00],
       [  6.68079806e+00,   0.00000000e+00,   0.00000000e+00],
       [  5.54582828e+00,   0.00000000e+00,   0.00000000e+00],
       [  4.51644310e+00,   0.00000000e+00,   0.00000000e+00],
       [  3.59264252e+00,   0.00000000e+00,   0.00000000e+00],
       [  2.77442654e+00,   0.00000000e+00,   0.00000000e+00],
       [  2.06179515e+00,   0.00000000e+00,   0.00000000e+00],
       [  1.45474836e+00,   0.00000000e+00,   0.00000000e+00],
       [  9.53286172e-01,   0.00000000e+00,   0.00000000e+00],
       [  5.57408577e-01,   0.00000000e+00,   0.00000000e+00],
       [  2.67115580e-01,   0.00000000e+00,   0.00000000e+00],
       [  8.24071800e-02,   0.00000000e+00,   0.00000000e+00],
       [  9.15635333e-03,   0.00000000e+00,   0.00000000e+00],
       [  1.01737259e-03,   0.00000000e+00,   0.00000000e+00],
       [  1.13041399e-04,   0.00000000e+00,   0.0000000

In [14]:
print(nlp.report(1))

NLP of type 'NLP_Factory' -- no reporting implemented
